apiVersion: v1
kind: Service
metadata:
  name: java-web-app-service
  namespace: java-web-app
spec:
  type: NodePort
  selector:
    app: java-web-app
  ports:
    - port: 80
      targetPort: 8082
      nodePort: 30082
